from app.schemas.domain import (
    DomainBase,
    DomainCreate,
    DomainUpdate,
    DomainResponse,
    DomainListResponse,
    CheckBase,
    CheckCreate,
    CheckResponse,
    CheckListResponse,
    IncidentBase,
    IncidentResponse,
    IncidentListResponse,
    DomainStats,
    StatusCount,
    DashboardSummary,
)

from app.schemas.settings import (
    ProxyServerBase,
    ProxyServerCreate,
    ProxyServerUpdate,
    ProxyServerResponse,
    ProxyServerListResponse,
    ProxyServerTestRequest,
    ProxyServerTestResponse,
    AppSettingBase,
    AppSettingCreate,
    AppSettingUpdate,
    AppSettingResponse,
    AppSettingListResponse,
    SecuritySettings,
    SettingsDashboardResponse,
)

__all__ = [
    # Domain schemas
    "DomainBase",
    "DomainCreate",
    "DomainUpdate",
    "DomainResponse",
    "DomainListResponse",
    "CheckBase",
    "CheckCreate",
    "CheckResponse",
    "CheckListResponse",
    "IncidentBase",
    "IncidentResponse",
    "IncidentListResponse",
    "DomainStats",
    "StatusCount",
    "DashboardSummary",
    # Settings schemas
    "ProxyServerBase",
    "ProxyServerCreate",
    "ProxyServerUpdate",
    "ProxyServerResponse",
    "ProxyServerListResponse",
    "ProxyServerTestRequest",
    "ProxyServerTestResponse",
    "AppSettingBase",
    "AppSettingCreate",
    "AppSettingUpdate",
    "AppSettingResponse",
    "AppSettingListResponse",
    "SecuritySettings",
    "SettingsDashboardResponse",
]
